version: '3'

services:
  mysql:
    image: mariadb
    networks:
      - inception-network
    build:
      context: /home/ndemont/Documents/inception/srcs/requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always
  nginx:
    image: nginx
    networks: 
      - inception-network
    build:
      context: /home/ndemont/Documents/inception/srcs/requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - wp-data:/var/www/html
    restart: always
  wordpress:
    image: wordpress
    networks:
      - inception-network
    build:
      context: /home/ndemont/Documents/inception/srcs/requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp-data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
       
volumes:
  wp-data:
    driver: local
    driver_opts:
      device: /home/ndemont/data/wp-data
      o: bind
      type: none
  db-data:
    driver: local
    driver_opts:
      device: /home/ndemont/data/db-data
      o: bind
      type: none

networks:
  inception-network:
