version: '3'
services:
  nginx:
    image: nginx
    networks: 
      - inception-network
    build:
     context: /home/ndmont/Documents/inception/srcs/requirements/nginx
     dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - wp-data:/www/

volumes:
        wp-data:
                driver: local
                driver_opts:
                        device: /home/ndmont/data/wp-data
                        o: bind
                        type: none

networks:
  inception-network:
