version: "2"
services:
  nginx:
    image: nginx
    networks: 
      - inception-network
    build:
     context: requirements/nginx/
     dockerfile: Dockerfile
    depends_on:
     - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ${HOME}/data/wp_data:/data
    restart: always
  db:
    image: mysql
    networks: 
     - inception-network
    build: 
     context: requirements/mariadb/
     dockerfile: Dockerfile
    volumes:
      - ${HOME}/data/db_data:/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress
    networks:
      - inception-network
    build:
     context: requirements/wordpress/
     dockerfile: Dockerfile
    volumes:
      - ${HOME}/data/wp_data:/data
    #restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
  wp_data: {}

networks:
  inception-network: