services:
  nginx:
    image: nginx
    build:
     context: requirements/nginx/
     dockerfile: Dockerfile
    ports:
      - "443:80"
    volumes: 
      - wp_data:/home/login/data
    restart: always
  db:
    image: mysql:5.7
    build: 
     context: requirements/mariadb/
     dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db_data:/home/login/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress
    build:
     context: requirements/wordpress/
     dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - wp_data:/home/login/data
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wp_data: {}