version: '3'

services:

  mariadb:
    image: mariadb
    networks:
      - inception-network
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  wordpress:
    image: wordpress
    env_file:
      - .env
    networks:
      - inception-network
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html
    restart: always

  nginx:
    image: nginx
    networks: 
      - inception-network
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - wp-data:/var/www/html
    restart: always

volumes:
  wp-data:
    driver: local
    driver_opts:
      device: /home/ndemont/data/wp-data
      o: bind
      type: none
  db-data:
    driver: local
    driver_opts:
      device: /home/ndemont/data/db-data
      o: bind
      type: none

networks:
  inception-network:
